name: PR Release

on:
  push:
    branches:
      - main
jobs:
  git-pr-release:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        target: [dev, stg]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: simple test
        run: [ -f tests/requirements2.txt ] && echo hi

      - name: Extract Python version from common.env
        id: get-python-runtime
        run: |
          PYTHON_RUNTIME=$(sed -n 's/^runtime="python\([0-9.]*\)".*/\1/p' vars/common.env 2>/dev/null)
          echo "python_runtime=${PYTHON_RUNTIME}" >> $GITHUB_OUTPUT

      - name: Setup Python
        if: steps.get-python-runtime.outputs.python_runtime != ''
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.get-python-runtime.outputs.python_runtime }}

      - name: python version
        if: steps.get-python-runtime.outputs.python_runtime != ''
        run: python -V

      - name: pip version
        if: steps.get-python-runtime.outputs.python_runtime != ''
        run: pip -V

      - name: Install dependencies if tests/requirements.txt exists
        run: test -f tests/requirements.txt && pip install -r tests/requirements.txt

      - run: pip list
