name: PR Release

on:
  push:
    branches:
      - main
jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [dev, stg]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -V
      - run: pip -V
